/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <dlfcn.h>
#include "logger.h"
//#include "ffmpeg.c"
/* Header for class com_lkland_videocompressor_Compressor */

#ifndef _Included_com_lkland_videocompressor_Compressor
#define _Included_com_lkland_videocompressor_Compressor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lkland_videocompressor_Compressor
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lkland_videocompressor_Compressor_getString
  (JNIEnv *env, jobject obj);

/*
 * Class:     com_lkland_videocompressor_Compressor
 * Method:    compress
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_lkland_videocompressor_Compressor_compress
  (JNIEnv *env, jobject obj, jobjectArray objArray);

#ifdef __cplusplus
}
#endif
#endif
